name: "MY CONTAINER ACTION"
description: "A simple container action that greets the user"
author: "prashant"

inputs:
  name:
    description: "The name of the person to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.name }}"
